{% set conda_name = "tabulator-py" %}
{% set name = "tabulator" %}
{% set version = "1.27.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "c722644b41f2b2a905f2eaaa8b0e8aab5e0d07e3ed69ac7eb7f681d8c2638627" %}
{% set build = 0 %}

package:
  name: {{ conda_name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}
build:
  noarch: python
  entry_points:
    - tabulator = tabulator.cli:cli

  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - six >=1.9,<2.0
    - click >=6.0,<7.0
    - requests >=2.8,<3.0
    - cchardet >=1.0,<2.0
    - unicodecsv >=0.14,<1.0
    - ijson >=2.0,<3.0
    - jsonlines >=1.1,<2.0
    - sqlalchemy >=1.1,<2.0
    - linear-tsv >=1.0,<2.0
    - xlrd >=1.0,<2.0
    - openpyxl >=2.4,<3.0
    - datapackage-py <1.0
    - ezodf >=0.3,<2.0
    - lxml >=3.0,<4.0

test:
  imports:
    - tabulator
    - tabulator.loaders
    - tabulator.parsers
    - tabulator.writers

  commands:
    - tabulator --help

about:
  home: https://github.com/frictionlessdata/tabulator-py
  license_file: LICENSE.md
  license: MIT
  license_family: MIT
  summary: 'Consistent interface for stream reading and writing tabular data (csv/xls/json/etc)'
  dev_url: https://github.com/frictionlessdata/tabulator-py

extra:
  recipe-maintainers:
    - pmlandwehr
